env:
  browser: true
  es2021: true
  node: true
extends:
 - eslint:recommended
 - plugin:jsdoc/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jsdoc
  - align-import
rules:
  align-import/align-import:
    - warn
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  no-multi-spaces:
    - error
    - exceptions:
        ImportDeclaration: True
  no-trailing-spaces:
    - warn
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  sort-imports:
    - warn
    - ignoreCase:
        true