version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "update-deployment"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8eaw058wq6uu"
s3_prefix = "update-deployment"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
